routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');

Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
Route::resource('categories','CategoryController');


Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::resource('books','BookController');
Route::get('/ajax/categories/search','CategoryController@ajaxSearch');

Route::resource('orders','OrderController');

//depan

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Category;
use App\Order;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;
    
    public function categories(){
        return $this->belongsToMany(Category::class);
    }

    public function orders(){
        return $this->belongsToMany(Order::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\Category;
use Str;
use Auth;
use Storage;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Gate;

class BookController extends Controller
{

    public function __construct()
    {
        $this->middleware(function($request, $next){

            if(Gate::allows('manage-books')) return $next($request);
          
            abort(403, 'Anda tidak memiliki cukup hak akses');
          });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // $books = Book::with('categories')->orderBy('id','desc')->get();
        $status = $request->get('status');
        $keyword = $request->get('keyword') ? $request->get('keyword') : '';

        if($status){
            $books = Book::with('categories')->where('title', "LIKE", "%$keyword%")->where('status', strtoupper($status))->orderBy('id','desc')->get();
        } else {
            $books = Book::with('categories')->where('title', "LIKE", "%$keyword%")->orderBy('id','desc')->get();
        }

        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
            "cover" => "required"
        ])->validate(); 

        $new_book = new Book;
        $new_book->title = $request->get('title');
        $new_book->description = $request->get('description');
        $new_book->author = $request->get('author');
        $new_book->publisher = $request->get('publisher');
        $new_book->price = $request->get('price');
        $new_book->stock = $request->get('stock');
        $new_book->status = $request->get('save_action');

        $cover = $request->file('cover');
        if ($cover) {
            $cover_path = $cover->store('book-covers','public');
            $new_book->cover = $cover_path;
        }

        $new_book->slug = Str::slug($request->get('title'));
        $new_book->created_by = Auth::user()->id;
        $new_book->save();
        $new_book->categories()->attach($request->get('categories'));

        if ($request->get('save_action') == 'PUBLISH') {
            return redirect()
                    ->route('books.create')
                    ->with('status','Buku berhasil disimpan dan dipublish');
        } else {
            return redirect()
                    ->route('books.create')
                    ->with('status','Book berhasil disimpan sebagai draft');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        return view('books.edit',compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $book = Book::findOrFail($id);

        \Validator::make($request->all(), [
            "title" => "required|min:5|max:200",
            "slug" => [
                "required",
                Rule::unique("books")->ignore($book->slug, "slug")
            ],
            "description" => "required|min:20|max:1000",
            "author" => "required|min:3|max:100",
            "publisher" => "required|min:3|max:200",
            "price" => "required|digits_between:0,10",
            "stock" => "required|digits_between:0,10",
        ])->validate();  

        $book->title = $request->get('title');
        $book->slug = $request->get('slug');
        $book->description = $request->get('description');
        $book->author = $request->get('author');
        $book->publisher = $request->get('publisher');
        $book->stock = $request->get('stock');
        $book->price = $request->get('price');

        // $new_cover = $request->file('cover');

        if ($request->file('cover')) {
            if (file_exists(storage_path('app/public/' . $book->cover))) {
                Storage::delete('public/'.$book->cover);
            }
            $file = $request->file('cover')->store('covers','public');
            $book->cover = $file;
        } else {
            $book->cover = $book->cover;
        }

        $book->updated_by = \Auth::user()->id;

        $book->status = $request->get('status');
        $book->slug = Str::slug($request->get('title'));

        $book->save();

        $book->categories()->sync($request->get('categories'));

        return redirect()->route('books.edit', [$book->id])->with('status', 'Buku Berhasil Di Ubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $book->delete();
        return redirect()->route('books.index')->with('status','Buku Berhasil Di Hapus Ke Dalam Tong Sampah');
    }

    public function trash(){
        $books = Book::onlyTrashed()->orderBy('id','desc')->get();
        return view('books.trash', compact('books'));
      }

      public function restore($id){
        $book = Book::withTrashed()->findOrFail($id);
      
        if($book->trashed()){
          $book->restore();
          return redirect()->route('books.trash')->with('status', 'Buku Berhasil Di Kembalikan');
        } else {
          return redirect()->route('books.trash')->with('status', 'Buku Tidak Berada Dalam Status tong sampah');
        }
      }

      public function deletePermanent($id){
        $book = Book::withTrashed()->findOrFail($id);
      
        if(!$book->trashed()){
          return redirect()->route('books.trash')->with('status', 'Buku tidak berada dalam status tong sampah')->with('status_type', 'alert');
        } else {
          $book->categories()->detach();
          $book->forceDelete();
      
          return redirect()->route('books.trash')->with('status', 'Buku berhasil didelete permanent!');
        }
      }
}

resources/views/books/create.blade.php
@extends('layouts.global')

@section('title-page')
     Data Buku
@endsection

@section('starter-page')
    Data Buku
@endsection

@section('content')
 <!-- Main content -->
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">

                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible">
                                <h6><i class="icon fa fa-ban"></i> Pesan !</h6>
                                <strong>{{ session('status') }}</strong>
                        </div> 
                    @endif
                   

                    <div class="card card-primary " >
                            <div class="card-header">
                              <h3 class="card-title">Form Tambah Data </h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form 
                                role="form"
                                enctype="multipart/form-data"
                                action="{{ route('books.store') }}" 
                                method="POST">

                            @csrf

                              <div class="card-body">

                                <div class="form-group">
                                  <label for="name">Judul</label>
                                  <input type="text" value="{{ old('title') }}"
                                  class="form-control {{ $errors->first('title') ? "is-invalid" : "" }}" id="title" name="title" placeholder="Masukan Judul Buku">

                                  @if ($errors->first('title'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('title') }}</strong>
                </div>
                @endif
                                </div>

                            
                                <div class="form-group">
                                        <label for="exampleInputFile">Cover Buku</label>
                                        <div class="input-group">
                                          <div class="custom-file">
                                            <input type="file" class="custom-file-input {{ $errors->first('cover') ? "is-invalid" : "" }}" id="cover" name="cover">
                                            <label class="custom-file-label" for="cover">Choose file</label>
                                          </div>
                                          <div class="input-group-append">
                                            <span class="input-group-text" id="">Upload</span>
                                          </div>
                                        </div>

                                        @if ($errors->first('cover'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('cover') }}</strong>
                </div>
                @endif
                                </div>

                                <div class="form-group">
                                    <label for="address">Deskripsi</label>
                                    <textarea  class="form-control {{$errors->first('description') ? "is-invalid" : ""}} "  id="description" name="description" rows="3" placeholder="Masukan Deskripsi  ...">
                                        {{old('description')}}
                                    </textarea>

                                    @if ($errors->first('description'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('description') }}</strong>
                </div>
                @endif
                            </div>

                            <div class="form-group">
                                <label for="name">Stok</label>
                                <input type="text" value="{{ old('stock') }}"
                                class="form-control {{ $errors->first('stock') ? "is-invalid" : "" }}" id="stock" name="stock" placeholder="Masukan Stok" min="0" value="0">

                                @if ($errors->first('stock'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('stock') }}</strong>
                </div>
                @endif
                              </div>

                              <div class="form-group">
                                <label for="name">Penulis</label>
                                <input type="text" value="{{ old('author') }}"
                                class="form-control {{ $errors->first('author') ? "is-invalid" : "" }}" id="author" name="author" placeholder="Masukan Penulis" >

                                @if ($errors->first('author'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('author') }}</strong>
                </div>
                @endif
                              </div>

                              <div class="form-group">
                                <label for="name">Penerbit</label>
                                <input type="text" value="{{ old('publisher') }}"
                                class="form-control {{ $errors->first('publisher') ? "is-invalid" : "" }}" id="publisher" name="publisher" placeholder="Masukan Penerbit" >

                                @if ($errors->first('publisher'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('publisher') }}</strong>
                </div>
                @endif
                              </div>

                              <div class="form-group">
                                <label for="name">Harga</label>
                                <input type="text" value="{{ old('price') }}"
                                class="form-control {{ $errors->first('price') ? "is-invalid" : "" }}" id="price" name="price" placeholder="Masukan Harga">

                                @if ($errors->first('price'))
                <div class="alert alert-danger alert-dismissible" style="margin-top:15px;">
                  <strong><i class="icon fa fa-ban"></i> {{ $errors->first('price') }}</strong>
                </div>
                @endif
                              </div>

                              <div class="form-group">
                                <label for="categories">Kategori</label>
                                <select name="categories[]" id="categories" class="form-control select2" multiple></select>

                             
                              </div>


                              <!-- /.card-body -->
              
                              <div class="card-footer">
                                <button  name="save_action" class="btn btn-primary" value="PUBLISH">Submit</button>
                                <button  name="save_action" class="btn btn-secondary" value="DRAFT">Simpan Sebagai Draft</button>
                              </div>

                              
                            </form>
                          </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
@endsection

@section('footer')
    <script>


        $('#categories').select2({
            ajax:{
                url: 'http://localhost:8000/ajax/categories/search',
                processResults:function(data) {
                    return {
                        results: data.map(function(item){return {id: item.id, text: item.name} })
                    }
                }
            }
        });

    </script>
@endsection

resources/views/books/index.blade.php
@extends('layouts.global')

@section('title-page')
     Data List Buku
@endsection

@section('starter-page')
    Data List Buku
@endsection

@section('header')
    <link rel="stylesheet" href=" {{ asset('assets/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
 <!-- Main content -->
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible">
                                <h6><i class="icon fa fa-ban"></i> Pesan !</h6>
                                <strong>{{ session('status') }}</strong>
                        </div> 
                     @endif

                    <a href="{{ route('books.create') }}" class="btn btn-info" style="margin-bottom: 10px;">Tambah Data</a>
                        <div class="card">
                                <div class="card-header">
                                  <h3 class="card-title">Buku</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                  
                                  <div class="row">
                                        
                                      <div class="col-md-4">
                                            <form action="{{ route('books.index') }}">
                                                <div class="form-group">
                                                        <input 
                                                        type="text" 
                                                        class="form-control" 
                                                        value="{{ Request::get('keyword') }}" 
                                                        id="keyword" 
                                                        name="keyword" 
                                                        placeholder="Filter berdasarkan judul">
                                                        
                                                    </div>
                                      </div>


                                      <div class="col-2"><button class="btn btn-info btn-block" type="submit"><i class="fa fa-search"></i> Filter</button></div>
                                    <div class="col-2"><a class="btn btn-info btn-warning btn-block" href="{{ route('books.index') }}"><i class="fa fa-search"></i> Clear</a></div>
                                    </form>

                                    <div class="col-md-4">
                                            <a class="btn btn-info " href="{{ route('books.index') }}"><i class="fa fa-eye"></i> All</a>
                                            <a class="btn btn-info " href="{{ route('books.index' , ['status' => 'publish']) }}"><i class="fa fa-eye"></i> Publish</a>
                                            <a class="btn btn-info " href="{{ route('books.index', ['status' => 'draft']) }}"><i class="fa fa-eye"></i> Draft</a>
                                            <a class="btn btn-danger " href="{{ route('books.trash') }}"><i class="fa fa-trash-o"></i> Trash</a>
                                        </div>
                                  </div>

                                  <table id="pengguna" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Cover Buku</th>
                                        <th>Judul</th>
                                        <th>Penulis</th>
                                        <th>Status</th>
                                        <th>Kategori</th>
                                        <th>Stok</th>
                                        <th>Harga</th>
                                        <th>Aksi</th>
                                        <th>Hapus</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    
                                    @forelse ($books as $book)
                                    <tr>
                                        <td>
                                            @if ($book->cover)
                                                <img src="{{ asset('storage/'.$book->cover) }}" alt="Foto Buku" width="50px">
                                            @else
                                                <img src="{{ asset('assets/dist/img/empty-user.png') }}" alt="Foto Buku" width="50px">
                                            @endif
                                        </td>
                                        <td>{{ ucfirst($book->title) }}</td>
                                        <td>{{ ucfirst($book->author) }}</td>
                                        <td>@if ($book->status == "DRAFT")
                                                <button class="btn" style="background: purple;color: white;">{{ $book->status }}</button>
                                            @else
                                                <button class="btn" style="background: brown;color: white;">{{ $book->status }}</button>
                                            @endif
                                        </td>
                                        <td>
                                            <ul class="pl-3">
                                                @foreach ($book->categories as $category)
                                                    <li>{{ $category->name }}</li>
                                                @endforeach
                                            </ul>
                                        </td>
                                        <td> {{ $book->stock }} </td>
                                        <td> {{ $book->price }} </td>

                                        <td>
                                            <a href="{{ route('books.edit', [$book->id]) }}" class="btn btn-warning" style="margin-right:10px;"><i class="fa fa-pencil"></i> Edit</a>
                                            <a href="{{ route('books.show', [$book->id]) }}" class="btn btn-info"><i class="fa fa-eye"></i> Detail</a>
                                        </td>
                                        <td>
                                                <form 
                                                action="{{ route('books.destroy', [$book->id]) }}"
                                                onsubmit="return confirm('Hapus data permanen ?')"
                                                method="POST">

                                                @csrf

                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Delete</button>
                                            </form>
                                        </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="5">Tidak ada data</td>
                                        </tr>
                                    @endforelse
                                    
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                            <th>Cover Buku</th>
                                            <th>Judul</th>
                                            <th>Penulis</th>
                                            <th>Status</th>
                                            <th>Kategori</th>
                                            <th>Stok</th>
                                            <th>Harga</th>
                                            <th>Aksi</th>
                                            <th>Hapus</th>
                                    </tr>
                                    </tfoot>
                                  </table>
                              
              </div>
  
            </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
@endsection


@section('footer')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
        $(function () {
          $("#pengguna").DataTable();
        });
      </script>
@endsection