routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('users', 'UserController');

Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/{category}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete-permanent');
Route::resource('categories','CategoryController');


Route::delete('/books/{id}/delete-permanent', 'BookController@deletePermanent')->name('books.delete-permanent');
Route::post('/books/{book}/restore', 'BookController@restore')->name('books.restore');
Route::get('/books/trash', 'BookController@trash')->name('books.trash');
Route::resource('books','BookController');
Route::get('/ajax/categories/search','CategoryController@ajaxSearch');

Route::resource('orders','OrderController');

//depan

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Book;

class Order extends Model
{
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function books(){
        return $this->belongsToMany(Book::class)->withPivot('quantity');
    }

    // DYNAMICE PROPERTY
    public function getTotalQuantityAttribute(){
        $total_quantity = 0;

        foreach($this->books as $book){
            $total_quantity += $book->pivot->quantity;
        }

        return $total_quantity;
    }


}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use Illuminate\Support\Facades\Gate;

class OrderController extends Controller
{

    public function __construct()
    {
        $this->middleware(function($request, $next){

            if(Gate::allows('manage-orders')) return $next($request);
          
            abort(403, 'Anda tidak memiliki cukup hak akses');
          });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $orders = Order::with('user')->with('books')->orderBy('id','desc')->get();

        $status = $request->get('status');
        $buyer_email = $request->get('buyer_email');

        $orders = Order::with('user')
                    ->with('books')
                    ->whereHas('user', function($query) use ($buyer_email) {
                        $query->where('email', 'LIKE', "%$buyer_email%");
                    })
                    ->where('status', 'LIKE', "%$status%")
                    ->orderBy('id','desc')
                    ->get();

        return view('orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::findOrFail($id);
        return view('orders.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id);
        $order->status = $request->get('status');
        $order->save();
        return redirect()->route('orders.edit', [$order->id])->with('status','Status Order Berhasil Di Ubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/orders/edit.blade.php
@extends('layouts.global')

@section('title-page')
     Data Order
@endsection

@section('starter-page')
    Data Order
@endsection

@section('content')
 <!-- Main content -->
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">

                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible">
                                <h6><i class="icon fa fa-ban"></i> Pesan !</h6>
                                <strong>{{ session('status') }}</strong>
                        </div> 
                    @endif
                   

                    <div class="card card-primary " >
                            <div class="card-header">
                              <h3 class="card-title">Form Edit Data </h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form 
                                role="form"
                                enctype="multipart/form-data"
                                action="{{ route('orders.update', [$order->id]) }}" 
                                method="POST">

                            @csrf

                            <input type="hidden" value="PUT" name="_method">


                              <div class="card-body">

                                <div class="form-group">
                                  <label for="name">No. Invoice</label>
                                  <input type="text" class="form-control" value="{{ $order->invoice_number }}" disabled>
                                </div>

                                <div class="form-group">
                                        <label for="name">Pembeli</label>
                                        <input type="text" class="form-control" value="{{ $order->user->name }}" disabled>
                                </div>

                                <div class="form-group">
                                        <label for="name">Tanggal Beli</label>
                                        <input type="text" class="form-control" value="{{ $order->created_at }}" disabled>
                                </div>

                                <div class="form-group">
                                        <label for="">Buku {{ $order->totalQuantity }}</label><br>
                                        @foreach ($order->books as $book)
                                                <li>{{ $book->title }} <b>{{ $book->pivot->quantity }}</b></li>
                                        @endforeach
                                </div>

                                <div class="form-group">
                                        <label for="name">Total Harga</label>
                                        <input type="text" class="form-control" value="{{ $order->total_price }}" disabled>
                                </div>

                                <div class="form-group">
                                        <label for="status">Status</label>
                                        <select class="form-control" name="status" id="status">
                                            <option {{ $order->status == "SUBMIT" ? "selected" : "" }} value="SUBMIT">SUBMIT</option>
                                            <option {{ $order->status == "PROCESS" ? "selected" : "" }} value="PROCESS">SUBMIT</option>
                                            <option {{ $order->status == "FINISH" ? "selected" : "" }} value="FINISH">SUBMIT</option>
                                            <option {{ $order->status == "CANCEL" ? "selected" : "" }} value="CANCEL">CANCEL</option>
                                        </select>
                                </div>

                              <!-- /.card-body -->
              
                              <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Ubah</button>
                              </div>
                            </form>
                          </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.global')

@section('title-page')
     Data List Order
@endsection

@section('starter-page')
    Data List Order
@endsection

@section('header')
    <link rel="stylesheet" href=" {{ asset('assets/plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
 <!-- Main content -->
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible">
                                <h6><i class="icon fa fa-ban"></i> Pesan !</h6>
                                <strong>{{ session('status') }}</strong>
                        </div> 
                     @endif

                    {{-- <a href="{{ route('orders.create') }}" class="btn btn-info" style="margin-bottom: 10px;">Tambah Data</a> --}}
                        <div class="card">
                                <div class="card-header">
                                  <h3 class="card-title">Order</h3>
                                </div>

                                <!-- /.card-header -->
                                <div class="card-body">
                                  
                                  <div class="row">
                                        
                                        <div class="col-md-4">
                                            <form action="{{ route('orders.index') }}">
                                                <div class="form-group">
                                                        <input 
                                                        type="text" 
                                                        class="form-control" 
                                                        value="{{ Request::get('buyer_email') }}" 
                                                        id="buyer_email" 
                                                        name="buyer_email" 
                                                        placeholder="Filter berdasarkan email pembeli">
                                                        
                                                    </div>
                                                </div>

                                                <div class="col-md-4">
                                                            <div class="form-group">
                                                                <select name="status" class="form-control" id="status">
                                                                        <option value="">ANY</option>
                                                                        <option {{Request::get('status') == "SUBMIT" ? "selected" : ""}} value="SUBMIT">SUBMIT</option>
                                                                        <option {{Request::get('status') == "PROCESS" ? "selected" : ""}} value="PROCESS">PROCESS</option>
                                                                        <option {{Request::get('status') == "FINISH" ? "selected" : ""}} value="FINISH">FINISH</option>
                                                                        <option {{Request::get('status') == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
                                                                </select>
                                                                </div>
                                                            </div>


                                      <div class="col-2"><button class="btn btn-info btn-block" type="submit"><i class="fa fa-search"></i> Filter</button></div>
                                    <div class="col-2"><a class="btn btn-info btn-warning btn-block" href="{{ route('orders.index') }}"><i class="fa fa-search"></i> Clear</a></div>
                                    </form>
                                  </div>

                                  <table id="pengguna" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>No Invoice</th>
                                        <th>Status</th>
                                        <th>Pembeli</th>
                                        <th>Total Quantity</th>
                                        <th>Tanggal Order</th>
                                        <th>Total Harga</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    
                                    @forelse ($orders as $order)
                                    <tr>
                                        <td>{{ $order->invoice_number }}</td>
                                        <td>@if ($order->status == "SUBMIT")
                                                <button class="btn btn-warning" >{{ $order->status }}</button>
                                            @elseif($order->status == "PROCESS")
                                                <button class="btn btn-info" >{{ $order->status }}</button>
                                            @elseif($order->status == "FINISH")
                                                <button class="btn btn-success" >{{ $order->status }}</button>
                                            @elseif($order->status == "CANCEL")
                                                <button class="btn btn-danger"  >{{ $order->status }}</button>
                                            @endif
                                        </td>
                                        <td>{{ $order->user->name }} <br> <small>{{ $order->user->email }}</small></td>
                                        <td>{{$order->totalQuantity}} pc (s)</td>
                                        <td>{{$order->created_at}}</td>
                                        <td>{{ $order->total_price }}</td>
                                        <td><a href="{{route('orders.edit', [$order->id])}}" class="btn btn-info btn-sm"> Edit</a></td>
                                        {{-- <td>{{ ucfirst($order->name) }}</td>
                                        <td>{{ $order->slug }}</td>
                                        <td>
                                            @if ($order->image)
                                                <img src="{{ asset('storage/'.$order->image) }}" alt="Foto Kategori" width="50px">
                                            @else
                                                <img src="{{ asset('assets/dist/img/empty-user.png') }}" alt="Foto Kategori" width="50px">
                                            @endif

                                        </td>
                                        <td>
                                            <a href="{{ route('orders.edit', [$order->id]) }}" class="btn btn-warning" style="margin-right:10px;"><i class="fa fa-pencil"></i> Edit</a>
                                            <a href="{{ route('orders.show', [$order->id]) }}" class="btn btn-info"><i class="fa fa-eye"></i> Detail</a>
                                        </td>
                                        <td>
                                                <form 
                                                action="{{ route('orders.destroy', [$order->id]) }}"
                                                onsubmit="return confirm('Hapus data ke tong sampah ?')"
                                                method="POST">

                                                @csrf

                                                <input type="hidden" name="_method" value="DELETE">

                                                
                                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Delete</button>
                                            </form>
                                        </td>
                                        </tr> --}}
                                    @empty
                                        <tr>
                                            <td colspan="5">Tidak ada data</td>
                                        </tr>
                                    @endforelse
                                    
                                    </tbody>
                                    <tfoot>
                                            <tr>
                                                    <th>No Invoice</th>
                                                    <th>Status</th>
                                                    <th>Pembeli</th>
                                                    <th>Total Quantity</th>
                                                    <th>Tanggal Order</th>
                                                    <th>Total Harga</th>
                                                    <th>Aksi</th>
                                                </tr>
                                    </tfoot>
                                  </table>
                              
              </div>
  
            </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
@endsection


@section('footer')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
        $(function () {
          $("#pengguna").DataTable();
        });
      </script>
@endsection